sudo:
  - required

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - make
  - rm -rf incnlo

deploy:
  provider: script
  script:
    - docker push akqf/incnlo
  on:
    tags: true
    all_branches: true
